INSERT ALL
  INTO Faculty(FId, FName) VALUES(1, 'Brick Wilson')
  INTO Faculty(FId, FName) VALUES(2, 'Willy Alistar')
  INTO Faculty(FId, FName) VALUES(3, 'Francesca DeWight')
  INTO Faculty(FId, FName) VALUES(4, 'Haley Khan')
  INTO Faculty(FId, FName) VALUES(5, 'Frank Biscuit')
  INTO Faculty(FId, FName) VALUES(6, 'Jasper Jenson')
  INTO Faculty(FId, FName) VALUES(7, 'Melory Archer')
  INTO Faculty(FId, FName) VALUES(8, 'Heidi Martini')
  INTO Faculty(FId, FName) VALUES(9, 'Jessy Jackson')
  INTO Faculty(FId, FName) VALUES(10, 'Flounder Corval')
  INTO Faculty(FId, FName) VALUES(11, 'Chip Jenson')
  INTO Faculty(FId, FName) VALUES(12, 'Anna Henrietta')
  INTO Faculty(FId, FName) VALUES(13, 'Geralt De Rivia')
  INTO Faculty(FId, FName) VALUES(14, 'Yen De Vengerberg')
  INTO Faculty(FId, FName) VALUES(15, 'Dandy Lion')
SELECT * FROM dual;