INSERT ALL
  INTO Course(CId, CName) VALUES('CS01', 'Intro to Programming')
  INTO Course(CId, CName) VALUES('CS02', 'Object Oriented Programming')
  INTO Course(CId, CName) VALUES('CS03', 'Data Structures')
  INTO Course(CId, CName) VALUES('CS04', 'Database Theory')
  INTO Course(CId, CName) VALUES('CS05', 'Advanced C++')
  INTO Course(CId, CName) VALUES('MATH01', 'College Algebra')
  INTO Course(CId, CName) VALUES('MATH02', 'Trigonometry')
  INTO Course(CId, CName) VALUES('MATH03', 'Linear Algebra')
  INTO Course(CId, CName) VALUES('MATH04', 'Calculus')
  INTO Course(CId, CName) VALUES('MATH05', 'Ordinary Differential Equations')
  INTO Course(CId, CName) VALUES('PHYS01', 'Physics For Scientists and Engineers')
  INTO Course(CId, CName) VALUES('PHYS02', 'Modern Physics')
  INTO Course(CId, CName) VALUES('PHYS03', 'Thermodynamics')
  INTO Course(CId, CName) VALUES('PHYS04', 'Quantum Mechanics')
  INTO Course(CId, CName) VALUES('PHYS05', 'Computational Physics')
SELECT * FROM dual;